package pl.edu.platinum.archiet.jchess3man.engine;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.Optional;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

/**
 * Created by Michał Krzysztof Feiler on 18.02.17.
 * FromToProm is a struct of [from], [to] and optionally [pawnPromotion] [FigType]
 * also storing it's generated [vecs] Iterable reference in it
 */
public class FromToProm extends FromTo {
    /**
     * the optional, i.e. nullable, pawnPromotion
     * current implementation probably should work with any non-null FigType always there
     * but it would look badly in the string representations
     */
    public final @Nullable FigType pawnPromotion;
    /**
     * whether generateVecs() was ever called and returned into [vecs]
     */
    protected boolean vecsAreGenerated = false;
    /**
     * vecs, the Iterable of vectors generated by generateVecs()
     * initially null, use after checking [vecsAreGenerated] or [areVecsGenerated()]
     */
    protected @Nullable Iterable<? extends Vector> vecs = null;

    /**
     * A constructor for FromToProm with null pawnPromotion
     *
     * @param from starting position
     * @param to   destination position
     */
    public FromToProm(Pos from, Pos to) {
        this(from, to, null);
    }

    /**
     * A constructor for FromToProm
     *
     * @param from          starting position
     * @param to            destination position
     * @param pawnPromotion optional pawnPromotion
     */
    public FromToProm(Pos from, Pos to, @Nullable FigType pawnPromotion) {
        super(from, to);
        this.pawnPromotion = pawnPromotion;
    }

    /**
     * @param obj object tested
     * @return whether obj is a FromTo and this.equals((FromTo) obj)
     */
    @Override
    public boolean equals(Object obj) {
        return obj instanceof FromTo && equals((FromTo) obj);
    }

    /**
     * @param b tested object
     * @return if b is a FromToProm return this.equals((FromToProm) b), else
     * whether this.pawnPromotion is null and b.equals(this)
     */
    @Override
    public boolean equals(FromTo b) {
        return b instanceof FromToProm
                ? equals((FromToProm) b)
                : pawnPromotion == null && b.equals(this);
    }

    /**
     * @param b tested object
     * @return whether this.equalsNoProm(b) and pawnPromotion is the same
     */
    public boolean equals(FromToProm b) {
        return equalsNoProm(b) &&
                (pawnPromotion == null && b.pawnPromotion == null ||
                        pawnPromotion != null &&
                                pawnPromotion.equals(b.pawnPromotion));
    }

    /**
     * @return hashcode composed of super.hashcode with bitwise left-shifted pawnPromotion
     */
    @Override
    public int hashCode() {
        return super.hashCode() | (FigType.toInt(pawnPromotion) <<
                ((finalBitSizeOfAPos << 1) + 1));
    }

    /**
     * @return string repr composed of [from]→[to]Þþ[pawnPromotion]
     */
    @Override
    public String toString() {
        return from.toString() + "→" + to.toString() + "Þþ" + FigType.string(pawnPromotion);
    }

    /**
     * @return whether generateVecs has finished already (i.e. vecsAreGenerated is true)
     */
    public boolean areVecsGenerated() {
        return vecsAreGenerated;
    }

    /**
     * stores fsq.vecs(from,to) in vecs field, runs checkPromotions and sets vecsAreGenerated to true
     *
     * @param fsq a Fig to call Fig.vecs(from,to) on
     * @throws NullPointerException       if fsq is null, I guess
     * @throws NeedsToBePromotedException if checkPromotions throws one, i.e.
     *                                    if pawnPromotion is null and promotion is required
     */
    public void generateVecs(@NotNull Fig fsq) throws NullPointerException, NeedsToBePromotedException {
        vecs = fsq.vecs(from, to);
        checkPromotions();
        vecsAreGenerated = true;
    }

    private void checkPromotions() throws NeedsToBePromotedException {
        boolean started = false;
        @Nullable ArrayList<PawnPromVector> theRet = null;
        assert vecs != null;
        for (final Vector vec : vecs) {
            if (vec instanceof PawnVector) {
                PawnVector pv = (PawnVector) vec;
                if (pv.reqProm(from.rank)) {
                    if (pawnPromotion == null)
                        try {
                            throw new NeedsToBePromotedException(new BoundVec(pv, from));
                        } catch (VectorAdditionFailedException e) {
                            throw new AssertionError(e);
                        }
                    started = true;
                    theRet = new ArrayList<>(2);
                }
                if (started) {
                    theRet.add(PawnPromVector.fromPawnVector(pv, pawnPromotion));
                }
            }
        }
        if (started) vecs = theRet;
    }

}
